### ISSUE TITLE
problem with 'emitWithAckWith' function 

### ISSUE THREAD

**Issue by StephaneGNT** [triniwiz/nativescript-socketio#105]
I am encountering an issue with socket.ios.ts, I keep getting this error `TypeError: this.socket.emitWithAckWith is not a function. (In 'this.socket.emitWithAckWith(event, payload)', 'this.socket.emitWithAckWith' is undefined).`

Nativescript-socketio is the  last available version (3.3.1) and ios is 14.6.
- CLI: 7.2.0

Any help would be greatly welcomed !

**Comment by triniwiz** [comment]
Have you tried @triniwiz/nativescript-socketio ?

**Comment by StephaneGNT** [comment]
yes, that is specifically what i am using

**Comment by StephaneGNT** [comment]
yes, that is specifically what i am using

**Comment by triniwiz** [comment]
Was wondering because you mentioned "Nativescript-socketio is the last available version (3.3.1)"

**Comment by StephaneGNT** [comment]
Yeah, I just realized the latest version according to your repo is not the same one than on the npm module linked to it (https://www.npmjs.com/package/nativescript-socketio) ; hence this 'mistake'.
Could this have a link with this emitWithAckWith not working ?

**Comment by triniwiz** [comment]
That version is correct this repo is currently for {N} v6 only, newer releases can be found [here](https://github.com/triniwiz/nativescript-plugins)

**Comment by StephaneGNT** [comment]
Yes, I am precisely working with {N} v6 (6.5.4 to be exact)

**Comment by triniwiz** [comment]
Ah okay you can still try the @triniwiz version it should just work since on the older version

**Comment by StephaneGNT** [comment]
Okay I'll try to take a look at it and come back to you ! Thanks for your fast answer anyway !!

**Comment by StephaneGNT** [comment]
Hi ! Sorry to bother you again ; how can I use your new release into my project ? Should I clone it and then build it ?
(Sorry, I'm really out of my comfort zone here ^^)

**Comment by triniwiz** [comment]
You need to install `@triniwiz/nativescript-socketio` an switch the imports to that

**Comment by StephaneGNT** [comment]
Indeed, thanks a lot for your help :) !
